{
 "title": "Desafio Claro - Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Cadastrado (Max 5)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pedidos_total" }
   ]
  },
  {
   "title": "Processando",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "pedidos_por_status{status=\"EM_PROCESSAMENTO\"}"
    }
   ]
  },
  {
   "title": "Pausados",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "pedidos_por_status{status=\"PAUSADO\"}"
    }
   ]
  },
  {
   "title": "Pedidos por Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "pedidos_por_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Capacidade (Limite de 5)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "pedidos_total", "legendFormat": "Pedidos Cadastrados" },
    { "expr": "5 - pedidos_total", "legendFormat": "Vagas Restantes" }
   ]
  }
 ]
}